name: Pylint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run pylint
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "pennylane"
          use-pylint: True
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--rcfile .pylintrc"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""

      - name: Check for new test files that need whitelisting
        uses: dorny/paths-filter@v2
        id: test_files_added
        with:
          list-files: shell
          filters: |
            testsAdded:
              - added: 'tests/**/test_*.py'
              - added: 'tests/test_*.py'

      - name: Ensure new test files are whitelisted if there are any
        if: steps.test_files_added.outputs.testsAdded == 'true'
        run: ./.github/workflows/scripts/validate_new_tests.sh ${{ steps.test_files_added.outputs.testsAdded_files }}

      - name: Read whitelisted test files that pass pylint
        id: tests_to_lint
        run: echo "testfiles=$(cat tests/tests_passing_pylint.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run pylint for whitelisted tests
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "${{ steps.tests_to_lint.outputs.testfiles }}"
          use-pylint: True
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--rcfile tests/.pylintrc"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
