name: NumPy 1 - Tests
on:

  schedule:
    # Runs daily at 6 AM UTC (1 AM Toronto in winter, 2 AM in summer)
    - cron: '0 6 * * *'  

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: numpy-1-unit-tests
  cancel-in-progress: true

jobs:
  numpy_1_tests:
    uses: ./.github/workflows/interface-unit-tests.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      branch: ${{ github.ref }}
      job_name_suffix: ' (numpy-1 compat)'
      run_lightened_ci: true
      additional_python_packages: 'numpy~=1.26.0'
      upload_to_codecov: false
      skip_ci_test_jobs: |
        all-interfaces-tests
        external-libraries-tests
        qcut-tests
        gradients-tests
        device-tests